### ISSUE TITLE
hi ,buddy

### ISSUE THREAD

**Issue by chillancezen** [adrian-bueno/hashtable#1]
appreciate for your work
I use your framework ,because I need to take an integer as my key  and void \* as my value ,so I changed your function embodiment ,besides ,I think you should preserve key interface :+1: 

same prototype like below:
int hashtable_delete_key(hashtable_t \* hashtable,int key)

**Comment by adrian-bueno** [comment]
Hello @chillancezen , thanks for using it! Sorry for not giving you a response earlier, I have not used the email I use with this Github account for some time and I didn't see you opened a new issue. I have improved the code, now keys can be of any type and I have added the function "hashtable_delete_key" too, plus other changes. I have also added 3 examples.
Greetings.
